<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
    <link href="<?php echo STATIC_DOMAIN;?>/css/style.css" type="text/css" rel="stylesheet">
    <link href="<?php echo STATIC_DOMAIN;?>/css/question.css" type="text/css" rel="stylesheet">
    <title>服务答疑</title>
</head>
<body>
<div class="content">
    <div class="event-question">
        <div class="tit text-left">我是买家</div>
    </div>
    <div class="question-content">
        <span class="buy"><em>买家：</em>我如何买票？</span>
        <span class="sell"><em>才府：</em>我们目前开通了才府APP内部的微信和支付宝支付渠道，您只需要使用手机即可直接购票。</span>
        <span class="buy"><em>买家：</em>订单可以退款吗？</span>
        <span class="sell"><em>才府：</em>除由于不可抗力因素或商家原因（如：活动取消、活动改期等）外，订单暂不支持退款，建议您尽量到现场观看或将票赠与朋友，谢谢谅解。<br>退款流程：用户通知平台冻结支付款项，与商家就退款事宜达成一致，商家退款，平台与商家结算款项。</span>
        <span class="buy"><em>买家：</em>我买好票了，到时候怎么用？</span>
        <span class="sell"><em>才府：</em>您买好票之后，在活动开始当天携手机到场馆入口处，打开已购买的票务订单详情即可由商家扫码，验票成功后入场。</span>
        <span class="buy"><em>买家：</em>这个演出不错，我想为家里人一起买票，可以吗？</span>
        <span class="sell"><em>才府：</em>同一个用户可以购买同一个活动（含不同价格）的多张票，您可以为家里人一起买票。</span>
        <span class="buy"><em>买家：</em>我可以把订单二维码发给朋友们吗？</span>
        <span class="sell"><em>才府：</em>我们是通过验证电子票二维码入场的，如果您将此二维码发给朋友，则您的朋友也可以验票入场，但为了保障您的权益，请妥善保管好电子票二维码，避免被非法盗用。</span>
        <span class="buy"><em>买家：</em>我买了好几张票，到现场后需要验好几次票吗？</span>
        <span class="sell"><em>才府：</em>我们的现场验票是一次性的，一个订单只能验票一次，如果您同一个订单中含有多张电子票，也只需验证一次，跟您购买的票数没有关系。</span>
    </div>
    <div class="event-question">
        <div class="tit text-left">我是卖家</div>
    </div>
    <div class="question-content">
        <span class="buy"><em>卖家：</em>发布付费活动需要申请吗？</span>
        <span class="sell"><em>才府：</em>需要，只有服务驿站的驿长才能发布付费活动，并且需要与上海代代传承文化传媒有限公司线下签约。</span>
        <span class="buy"><em>卖家：</em>你们的佣金是怎么收取的？</span>
        <span class="sell"><em>才府：</em>不同的活动类目佣金不同，具体以线下合约为准。</span>
        <span class="buy"><em>卖家：</em>我是驿长，我的收入如何兑现？</span>
        <span class="sell"><em>才府：</em>我们将在每个月月初与合作驿站开启对账工作，与才府签约的驿站驿长每个月初都会收到才府工作人员的对账邮件，包含上个自然月本驿站发布活动的成功支付订单金额明细、佣金比例、扣除协议佣金后的实际款项等，我们将在双方对账确认后，按约定日期将实际款项汇至合约指定银行账户。</span>
        <span class="buy"><em>卖家：</em>有几种票务类型？</span>
        <span class="sell"><em>才府：</em>我们在原有的活动基础上开放了才府支付渠道，现有免费和付费两种类别。</span>
        <span class="buy"><em>卖家：</em>我可以发布几个活动？</span>
        <span class="sell"><em>才府：</em>我们对驿站发布的活动总数量不做限制，但是同一个活动的价格种类不应超过10个（包含10个）。</span>
        <span class="buy"><em>卖家：</em>我可以退出合作吗？</span>
        <span class="sell"><em>才府：</em>如您因个人原因、不可抗力等原因需要终止合作，请提前与才府商务对接人联系，才府将于约定的工作日内将剩余结算款项汇至您指定账户，一般来说，合约期不应低于1年，具体以双方协议约定为准。</span>
        <span class="sell"><em></em>如您有更多问题，请联系<a href="<?php echo I_DOMAIN;?>/chat/user/8931">才府小管家。</a></span>
    </div>
    <div class="hei20"></div>
</div>
</body>
</html>