<?php include_once VIEWS_PATH."/public/commonHead.phtml";?>
<body>
<div class="header_top" id="head-nav">
    <div class="tiezi_toptar" style="border-bottom-color: rgba(217, 217, 217, 0); background: rgba(255, 255, 255, 0);">
        <ul>
            <li class="tb_btn btn1">
                <a href="/fanhui" id="mc-back" class="top-back"></a>
            </li>
            <li class="tb_btn btn2" onclick="previewOperation()">
                <a id="mc-reset" class="top-reset"></a>
            </li>
            <li class="tb_btn btn3" onclick="previewOperation()">
                <a id="mc-share" class="top-share"></a>
            </li>
        </ul>
    </div>
</div>
<!--toptar  ed-->
<div class="scroll" id="scroll">
<div id="slideBox" class="slideBox">
    <!--banner图底部内阴影-->
    <div class="slideBox_shadow"></div>
    <div class="bd" id="pic">
        <div class="tempWrap" style="overflow:hidden; position:relative;text-align: center">
            <img id="mc-img" src="<?php echo IMG_DOMAIN.$goodsInfo['cover'];?>">
        </div>
    </div>
</div>
<!--top_banner  ed-->
<div class="tiezi_cotent fuwu_cotent">
    <div class="tz_box product_box1">
        <p class="tz_tit">
            <?php echo $goodsInfo['name'];?>
        </p>
        <ul class="product_price clearfix">
            <?php if($goodsInfo['type']==1){?>
                <li class="pr1">￥<?php echo $goodsInfo['price'];?></li>
            <?php }elseif($goodsInfo['type']==2){?>
                <li class="pr1"><i class="pr1_blessing"></i><?php echo $goodsInfo['score'];?>&nbsp;+￥<?php echo $goodsInfo['price'];?></li>
            <?php }elseif($goodsInfo['type']==3){?>
                <li class="pr1"><i class="pr1_blessing"></i><?php echo $goodsInfo['score'];?></li>
            <?php }?>
            <li class="pr2"><?php echo $goodsInfo['address_name'];?>
            </li>
        </ul>

    </div>
    <!--标题  ed-->
    <div class="tz_box tz_box2 fuwu_box2">
        <div class="tz_p">
            <?php echo str_replace("\n","<br>",$goodsInfo['intro']);?>
        </div>
        <p class="tz_ban">本文的所有图、文等著作权及所有权归原作者所有<a>举报</a></p>
        <!-- 喜欢列表 -->
        <div class="tz_zan">
            <div class="tz_zan_s">
                <a>
                    <span id="like_status" class="zan_gray" onclick="previewOperation()"></span>
                    <p class="like"><span id="like_num">0人</span>喜欢</p>
                </a>
            </div>
            <p class="tz_zan_no">您的喜欢是对我最大的鼓励</p>
        </div>
        <!-- 喜欢列表end -->
    </div>
    <!--详情介绍  ed-->
</div>
<!--购买记录  ed-->
<div class="tz_box tz_box4" style="margin-bottom: 40px">
    <div class="tz_box_title clearfix">
        <li class="x1"><img src="<?php echo STATIC_DOMAIN;?>/images/topic/tie-btn7.jpg"></li>
        <li class="x2">评论</li>
        <li class="x1"><img src="<?php echo STATIC_DOMAIN;?>/images/topic/tie-btn7.jpg"></li>
    </div>
    <div class="tz_pinglun">
        <div class="pl_message">
            <div class="mes_top">
                <p class="mes_bg">
                     </p>
                <p class="mes_photo"><img src="<?php echo Common::show_img($goodsInfo['stageInfo']['icon'],2,100,100);?>"></p>
            </div>
            <p class="mes_name"><?php echo $goodsInfo['stageInfo']['name'];?></p>
            <p class="mes_fensi"></p>
            <ul class="fuwu_zhidian clearfix">
                <li><a><img src="<?php echo STATIC_DOMAIN;?>/images/topic/fuwu-ico5.png">致电客服</a></li>
                <li class="fuwu_xian"><img src="<?php echo STATIC_DOMAIN;?>/images/topic/zt-btn2.png"></li>
                <li><a><img src="<?php echo STATIC_DOMAIN;?>/images/topic/fuwu-ico6.png">进入驿站</a></li>
            </ul>
        </div>
    </div>
</div>
<!--评论 ed-->
</div>
</div>
<!--tiezi_content  ed-->
<div class="footers">
    <div class="tiezi_bottom clearfix">
        <ul>
            <li class="bbtn1" onclick="previewOperation()"><a><span class="bottom_ico bottom_ico_rewrad"></span>咨询</a></li>
            <li class="bbtn2" onclick="previewOperation()" id="like_li_status" ><a id="like_a_status"><span class="bottom_ico bottom_ico_like"></span>收藏</a></li>
            <li class="bbtn3" onclick="previewOperation()"><a><span class="bottom_ico bottom_ico_post"></span>驿站</a></li>
            <li class="bbtn4" onclick="previewOperation()"><a>立即购买</a></li>
        </ul>
    </div>
</div>
<!--tiezi_bottom  ed-->
<!--底部弹层操作项 -->
<script>
    var scrollable = document.getElementById("scroll");
    new ScrollFix(scrollable);
</script>
</body>
</html>