<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
    <link href="<?php echo STATIC_DOMAIN;?>/css/style.css" type="text/css" rel="stylesheet">
    <link href="<?php echo STATIC_DOMAIN;?>/css/question.css" type="text/css" rel="stylesheet">
    <title>有奖分享规则</title>
</head>
<body>
<div class="content">
    <div class="agreement-content">
        <div>一、推广说明</div>
        1、如何让分享推广<br>
        进入相应的分享商品或者活动页面，点击“分享”按钮，选择需要分享的渠道。<br><br>
        2、目前支持那些分享渠道<br>
        目前支持微信好友、微信朋友圈、QQ好友、QQ空间、新浪微博，也可以分享到文化圈或者分享给知己直接把链接发送给朋友。<br><br>
        3、如何才算有效分享<br>
        他人只要从您的分享出去的链接下单购买，都属于有效分享。<br><br>
        <div>二、推广规则</div>
        1、什么样的订单才是有效订单<br>
        已经支付或者确认收货，未被取消或者关闭的订单都是有效订单。<br><br>
        2、奖金比例是多少<br>
        拥挤比例由驿长自行设定。<br><br>
        3、奖金什么时候结算<br>
        待分享出去的商品或者活动确认收货后，奖金会自行打款至您的钱袋。<br><br>
        4、奖金可以提现<br>
        分享的奖金到达100元后才可进行提现。<br><br>
        5、个税规则<br>
        根据我国法律及税收政策，用户有义务就本人在平台上的劳务报酬所得按时、足额的缴纳相关税费。“才府”平台有权随时根据税务部门的最新政策或指导意见，即时调整用户税款缴纳问题的执行方式及相关规定。<br><br>
        6、分享成功后奖金被修改或者关闭了<br>
        1）如驿长中途调整了奖金比例，之前用户分享的链接在5天内有效。如果在5天内有生成订单依旧扣除相应的奖金比例。<br><br>
        2）关闭分享有奖之后，之前用户分享的链接将在5天内有效，如果在5天内生成订单，依旧扣除相应的奖金。<br><br>
        7、现金购+福报值<br>
        现金购+福报值只计算现金不计算福报值。<br><br>
        8、没有收到奖金<br>
        由于3.8版本增加分享有奖功能，故使用3.8版本以前的用户，通过分享链接购买商品，没有奖金。<br><br>
        更多细则请阅读：<a class="blue" href="/common/sellerShareAgreement">《分享有奖协议》</a>
    </div>
    <div class="hei40"></div>
</div>
</body>
</html>