<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/lib/jquery-1.8.0.min.js?v=<?php echo STATIC_FILE_VERSION;?>"></script>
    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/lib/artDialog.js?v=<?php echo STATIC_FILE_VERSION;?>"></script>
    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/page/common.js?v=<?php echo STATIC_FILE_VERSION;?>"></script>
    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/lib/scrollfix.js?v=<?php echo STATIC_FILE_VERSION;?>"></script>
    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/page/operation.js?v=<?php echo STATIC_FILE_VERSION;?>"></script>
    <?php if(isset($app_css) && count($app_css)>1){
        foreach($app_css as $key=>$val){?>
            <link href="<?php echo STATIC_DOMAIN;?>/css/<?php echo $val;?>.css?v=<?php echo STATIC_FILE_VERSION;?>" type="text/css" rel="stylesheet" />
        <?php }
    }elseif(isset($app_css)){?>
            <link href="<?php echo STATIC_DOMAIN;?>/css/<?php echo $app_css;?>.css?v=<?php echo STATIC_FILE_VERSION;?>" type="text/css" rel="stylesheet" />
        <?php
    } ?>
    <link href="<?php echo STATIC_DOMAIN;?>/css/common.css?v=<?php echo STATIC_FILE_VERSION;?>" type="text/css" rel="stylesheet" />
    <script>
        window.$userInfo = <?php if(isset($user)){echo json_encode($user);}else{echo json_encode(array());}?>;
    </script>
    <title><?php if(isset($page_title)){echo $page_title;}else{echo "才府";}?></title>
</head>