<!--
<div class="share-box layout-box">
    <?php if($is_collect ==0){?>
    <a class="son-box" href="/collect/type/<?php if(isset($eventInfo)){echo '2/id/'.$eventInfo['id'];}elseif(isset($topicInfo)){echo '1/id/'.$topicInfo['id'];}else{echo '3/id/'.$blog['id'];}?>">
        <i class="collect-ico"></i>
        <p>收藏</p>
    </a>
    <?php }else{?>
    <a class="son-box">
        <i class="collect-ico on"></i>
        <p>已收藏</p>
    </a>
    <?php }?>
    <a class="son-box" href="/pengyouquan/title/<?php echo $page_title?>/img/<?php echo $stageImg?>/description/<?php echo $description?>">
        <i class="wechat-ico"></i>
        <p>微信朋友圈</p>
    </a>
    <a class="son-box" href="/friend/title/<?php echo $page_title?>/img/<?php echo $stageImg?>/description/<?php echo $description?>">
        <i class="wechat-fri-ico"></i>
        <p>微信好友</p>
    </a>
    <a class="son-box" href="/sina/title/<?php echo $page_title?>/img/<?php echo $stageImg?>/description/<?php echo $description?>">
        <i class="sina-ico"></i>
        <p>新浪微博</p>
    </a>
</div>
-->

