<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
    <script src="<?php echo STATIC_DOMAIN;?>/js/lib/appframework/appframework.js" type="text/javascript"></script>
    <script src="<?php echo STATIC_DOMAIN;?>/js/lib/appframework/plugins/af.popup.js" type="text/javascript"></script>

    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/page/common.js"></script>
    <link href="<?php echo STATIC_DOMAIN;?>/css/style.css" type="text/css" rel="stylesheet">
    <title>成员</title>
</head>
<body>
<div class="content" id="loginMemberList">
<?php include_once VIEWS_PATH."/stage/loginMemberList.phtml";?>
</div>
<script>
    $(document).ready(function(){
        $('.fans-list').delegate('.fans-btn.add-btn','click',function(){
            var self = $(this);
            ajaxPost('/follow/addFollow',{f_uid:self.data('uid'),token:token},function(data){
                if(data == 1) {
                    self.parent().append('<div class="fans-btn font-ico focus-btn"><i></i>已关注</div>');
                    self.remove();
                } else if(data == 2) {
                    self.parent().append('<div class="fans-btn font-ico friend-btn"><i></i>知己</div>');
                    self.remove();
                } else {
                    console.log(data);
                }
            },function(data){
                if(data.status == 403) {
                    backLogin();
                } else {
                    tips(data.message);
                }
            });
        });
    });
</script>
<?php if($memberNum > 13) {?>
    <div class="footer-loading" id="loadMore"><img src="<?php echo STATIC_DOMAIN;?>/images/loading.gif" height="35" width="35"></div>
    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/page/contentloader.js"></script>
    <script>
        $(document).ready(function(){
            var opts = {
                loadType:1,//1、页面到达底部自动加载 2、点击更多进行加载
                isShowPage:false,//是否显示分页
                loadNumBeforeShowPage:6,//显示分页前的加载次数
                loadMoreBtn:$('#loadMore'),//加载更过按钮或者loading图标
                pageSize:13,
                pageNum:2,
                sid:<?php echo $sid;?>,
                size:<?php echo $memberNum;?>,
                token:'<?php echo $token?>',
                list:$("#loginMemberList"),
                template:function(data){
                    return data.data;
                }
            }
            $.fn.loadMore('/stage/loginMemberMore',{page:opts.pageNum,size:opts.pageSize,sid:opts.sid,token:opts.token},opts);
        });
    </script>
<?php }?>
</body>
</html>