
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
    <script src="<?php echo STATIC_DOMAIN;?>/js/appframework.js" type="text/javascript"></script>
    <link href="<?php echo STATIC_DOMAIN;?>/css/style.css" type="text/css" rel="stylesheet">
    <link href="<?php echo STATIC_DOMAIN;?>/css/stage.css" type="text/css" rel="stylesheet">
    <title>商业驿站首页</title>
</head>
<body class="gary-bg">

<div class="qr-show-box">
    <div class="con">
        <div class="box"><img src='<?php echo $qrcode?>'></div>
        <p>扫一扫上面的二维码图案加入驿站</p>
    </div>
</div>

</body>
</html>