<?php include_once VIEWS_PATH."/public/commonHead.phtml";?>
<link href="<?php echo CSS_DOMAIN;?>/css/peoplescultural.css" type="text/css" rel="stylesheet">
<body>
<div class="scroll" id="scroll">
    <div id="banner" class="banner" ></div>
    <div class="back-con"></div>
    <div class="peo-con">
        上海戏剧学院院长、舞美系教授、博士生导师、中国著名舞美设计家。中国剧协副主席、中国舞台美术学会副会长、中国话剧研究会副会长、上海舞台美术学会会长、上海市文联委员、上海戏剧家协会常务理事、上海电视艺术家学会理事、上海市文广局文化科技委员会主任委员。长期从事舞台美术创作与教学，现任第八届中国剧协副主席。
    </div>
    <div class="peo-title">
        <span></span>
        教书育人 传承戏剧文化
        <span></span>
    </div>
    <div class="peo-img">
        <img src="../images/people.png">
    </div>
    <div class="peo-con">
        中国传统文化中，戏剧是非常重要的表现形式之一。在漫长的历史传承中，中国戏剧形成了属于自己的表演体系与审美特质。中国古代戏剧记录并十分精彩地呈现了丰富的民间传说故事，承载并传承着中华民族的文化精神与历史记忆。
    </div>
    <div class="peo-img">
        <img src="../images/sahnghaiaddress.png">
    </div>
    <div class="peo-con">
        上海戏剧学院是中国著名的戏剧学府，韩生在该校担任院长、舞美系教授及博士生导师，为热爱戏剧、热爱舞台艺术的后生学子们传授宝贵知识，作出悉心指导。他任院长的上海戏剧学院多年来培养了诸如胡歌、李冰冰、廖凡、冯绍峰等诸多优质戏剧影视明星，为中国的戏剧影视事业做出巨大贡献。
    </div>
    <div class="peo-img">
        <img src="../images/people1.png">
    </div>
    <div class="peo-con">
        韩生传道授业解惑的同时，为多部优秀的话剧、传统戏剧作品担当美术设计，主要作品有话剧《大桥》、越剧《家》、《蝴蝶梦》、赣剧《牡丹亭》，超大型景观歌剧《阿依达》等，还曾担任了电影《兰陵王》美术设计。
    </div>

    <div class="peo-title">
        <span style="margin:0 16px 12px 0;"></span>
        <i>
            舞台艺术的设计大师<br/>
            展现文化盛宴
        </i>
        <span style="margin:0 0 12px 16px;"></span>
    </div>
    <div class="peo-con">
        一场大获赞誉的文艺演出，优秀的舞台艺术设计不可或缺。舞台美术是戏剧和其他舞台演出的一个重要组成部分，包括布景、灯光、化妆、服装、效果、道具等，它们的综合设计称为舞台设计。其任务是根据剧本的内容和演出要求，在统一的艺术构思中运用多种造型艺术手段，创造出剧中环境和角色的外部形象，渲染舞台气氛。
    </div>
    <div class="peo-img">
        <img src="../images/people3.png">
    </div>
    <div class="peo-con">
        韩生，在舞台美术设计上大有建树，担纲和参与了多次重大文艺演出的相关设计。<br />
        　　2001年亚太经合组织（APEC）系列会议在我国举行，这次会议在当时，是建国以来我国承办的规模最大、层次最高的国际会议，韩生担任了这次国际会议文艺演出的美术总设计师，呈现了一场精彩的富有中国传统美的文化盛宴。
    </div>
    <div class="peo-img">
        <img src="../images/beijing.png">
    </div>
    <div class="peo-con">
        2008年，举世瞩目的北京第二十九届奥林匹克运动会开幕式在国家体育场（鸟巢）举行，奉献给全世界一台经典的奥林匹克视听盛宴，韩生参加了北京奥运会开幕式的设计创作工作。具有两千多年历史的奥林匹克运动与五千多年传承的灿烂中华文化交相辉映，共同谱写人类文明气势恢弘的新篇章。
    </div>
    <div class="peo-img2">
        <img src="../images/wutai.png">
    </div>
    <div class="peo-con">
        在舞台设计学术上，韩生著有《舞台空间的魅力——舞台设计的创意和表现》。该书收录了韩生近三十个剧目及开幕式晚会的设计创作回忆，分享了舞台设计的创意思路和艺术技巧。
    </div>
    <div class="peo-img">
        <img src="../images/people4.png">
    </div>
    <div class="peo-con">
        几十年如一日的辛勤付出与努力，让韩生获得了实至名归的荣誉：曾获文化部第二届、第四届“文华舞台美术奖”,中国话剧舞台美术“金狮奖”,第二届中国舞台美术展览会“设计大奖”,“宝钢艺术奖”,“宝钢优秀教师奖”,“国家级教学成果二等奖”和“上海市教学成果一等奖”,先后被评为“文化部优秀专家”、“上海市领军人才”、“曙光学者”等，享受国务院特殊津贴。
    </div>
    <div class="peo-img">
        <img src="../images/people5.png">
    </div>
    <div class="peo-con">
        2015年7月16日，中国戏剧家协会第八次全国代表大会在北京闭幕，此次大会主旨为坚持以人民为中心的工作导向为实现中国梦唱响中国戏剧的最强音，大会选举韩生为第八届中国剧协副主席。
    </div>
    <div class="peo-personal">
        <div class=" head-portrait">
            <div class="head-portrait-con">
                <img src="../images/header.png"/>
            </div>
        </div>
        <p class="cir"><i></i>韩正</p>
        <p class="fansi-con">粉丝:304 | 关注:479</p>
        <span class="enter">进入主页</span>
    </div>
    <div class="review">
        <span></span>
        往期回顾
        <span></span>
    </div>
    <div class="peo-img1">
        <img src="../images/people6.png">
        <p>沈伟媛</p>
        <span>收藏女王24年成就一件事</span>
    </div>
</div>

</body>
</html>