<?php include_once VIEWS_PATH."/public/commonHead.phtml";?>
<link href="<?php echo CSS_DOMAIN;?>/css/peoplescultural.css" type="text/css" rel="stylesheet">
<body>
<div class="scroll scroll-z" id="scroll">
    <div id="banner" class="banner1" ></div>
    <div class="back-con-z"></div>
    <div class="peo-con">
        他常年一袭素衣着身，泰然洒脱，谈吐自然朴真，通俗而不失理趣。他被人誉为“当代庄子”，二十年醉心于老庄研究，幡然悟道。<br>
        　　他是连山堂堂主、竹山书院山长、坐忘山秋浦书院、象罔书院山长，在全国授课讲学备受欢迎，在弘扬道源文化的路途中义无反顾地前行。
    </div>
    <div class="peo-img">
        <img src="../images/zhangzhen1.png">
    </div>
    <div class="peo-con">
           他叫张真，1972年生于蒙城一个普通家庭，毕业于安徽大学经济管理系，曾供职于合肥郊区报。和天地相比，人生确实太短，但总有人能在“忽然”的某个时刻决定一件足以改变一生的事。1996年，张真瞒着家人，辞去前景光明的工作，独自一人租住在一个没有窗户，冬天枕头都会发霉的房子里，一日只啃三个馒头的状况下，开启了学画悟道之路。
    </div>

    <div class="profile">
        <img src="../images/zhangzhen-title.png">
    </div>

    <div class="peo-con">
        “人生的幸福与否，在于是否错位，如果做了喜欢做的，无论穷达都会有幸福感，有四五天我都在考虑，觉得自己还是比较喜欢画画，不适合干其他的事情。”最初学习绘画，他以临摹其他人作品为主，后期曾到中央美院、四川美院进修，终因某些原因放弃。他的观念里，中国绘画的至高境界是在中国文化背景下产生的，它是画家以画证道的结果。现在的问题是，越来越多的人是在用想法和情绪在画画，用的是虽然还是宣纸，但画的已不是有中国文化大雅之境，文化道统缺失了。
    </div>
    <div class="peo-img">
        <img src="../images/zhangzhen2.png">
    </div>
    <div class="peo-con">
        那之后有段时间，张真在别人眼中成了年纪轻轻在家不干活，也不画画，是天天“想入非非”的怪人，他说“中国的文化，应是在道的语境中展开的。很长时间，我们一提到道，就觉得是消极，是迷信的，其实不是这么回事。而我自己觉得与其看画论，通过二道贩子来体悟道，不如直接研究老庄。”从而开启了潜心研究老庄智慧道路，而一研究就是二十几年，阅读了大量著作后，他还将纸上得来的智慧同时也躬行实践，1997到2000年，他大量时间都是在读书和行走，并且基本上把中国走了一遍。
    </div>
    <div class="peo-img">
        <img src="../images/zhangzhen3.png">
    </div>
    <div class="peo-con">
        最长的一次行走，历时九个月，他带着三千块，背着画夹、行李，从秦皇岛海边向西，走到重庆，沿着黄河走，让灵魂沐浴在阳光之下，接受天地之灵，他走遍夏商周故地，又去了中国绘画史上的三大高峰代表人物——荆浩、范宽、李成的故地，他想知道那些顶级的大画家看到的山川和我们今天看到的有什么不同，是什么力量令他们画出的画能让人的灵魂都觉得安定。带着满腹的疑问，他独自行走在山川大地间，全神贯注，默默思考着，不被任何人打扰，路漫漫其修远兮，这求知探索的过程给了他人生宝贵的积淀。
    </div>
    <div class="peo-img1">
        <div class="peo-img1-con" style="padding:0.5rem;background: #fff">
            <img src="../images/pic.png">
        </div>
    </div>

    <div class="back1-con">
        <!--<img src="../images/back2.png">-->
    </div>

    <div class="peo-con">
        “走过多少名山大川不是很重要，重要的是我为什么要走。”行走、思考、体悟让他的画艺从“技”进“道”的转变。古今中外，大凡伟大的艺术家，都有一颗真诚的心灵，只有这颗真诚才能超越穷达利害。看古人的山水画，可以见到古人的心力，他们的心如太虚一般，笼罩着大地。
    </div>
    <div class="peo-img">
        <img src="../images/zhangzhen4.png">
    </div>
    <div class="peo-img">
        <img src="../images/pic1.png">
    </div>
    <div class="peo-con">
        大音希声，和牛群以及聋哑学生的缘分是张真人生的另一次关键点。牛群到蒙城就任后，来到张真仅有一条板凳，一张床，一个画案的简陋画室，两人席地促膝长谈，成就了一段和聋哑学生的画缘，不但让那些学生生命得以绽放，也为张真打开了新世界的大门。这些聋哑学生的画作2014年在上海展览后，引起圈内的震动。
    </div>
    <div class="peo-img1">
        <img src="../images/pic3.png">
    </div>
    <div class="back2-con">

    </div>
    <div class="peo-con">
        和聋哑人的接触，让张真对生命有了全新的理解，在他看来，生命本来是灿烂的，作为有文化担当的人，最重要的是提供文化氛围，这就是圣人说的“世风”，世风是会影响国运的，所以当越来越多的人为“世风”作良性推动的时
        候，一切都会好起来，譬如雾霾，环境一旦变得恶劣，谁都逃不掉，如果人人都自律，必能改善，人心如此，教育也是一样。教育最重要的是提供一个让人能够自我绽放的时空，而不是教他什么。    </div>
    <div class="peo-img">
        <img src="../images/zhangzhen5.png">
    </div>
    <div class="peo-img">
        <img src="../images/zhangzhen6.png">
    </div>
    <div class="peo-con">
        从大音堂到连山堂，再到担任竹山书院山长、象罔书院山长，张真以“但行好事，莫问前程”泰然洒脱的心态投身教育事业。他常言“庄敬身心，庄严国土。托不得已以养中。君子不可以不刳心焉。愚者张真愿与诸仁，炮庄发
        药，自事其心。”对于张真来说，他要做的，不是一个形式意义上的书院，不是一个企业，不是一个文化产业，而是一个可以聚徒讲学的地方，但他觉得在这个时空下是不可能的，所以现在是在做“知不可能还必须做的事情”。明知不可为而为之，焉知上天不会对生命有意外的馈赠？在这种宁静平和的心态下，他不去想维持多长时间，有一天就负责一天，有一天就真心实意地做一天，他在意的是自己能不能饱满地度过每一天。
    </div>
    <div class="peo-img">
        <img src="../images/sun.png">
    </div>
    <div class="peo-img">
        <img src="../images/zhangzhen7.png">
    </div>
    <div class="peo-con">
        老子言：知人者智，自知者明。庄子言：终身言，未尝言，终身不言，未尝不言。张真被称为“当代庄子”，他谦逊虔诚，他践行“知不知，不在言不在默”。以生命证道，以行动宏道。先贤不再，来者可期，旷古幽思，不曾断绝。
    </div>
    <div class="peo-img">
        <img src="../images/pic4.png">
    </div>
    <div class="peo-img">
        <img src="../images/shanshui_05.png">
    </div>
    <div class="back3-con">

    </div>

    <div class="peo-personal">
        <div class=" head-portrait">
            <div class="head-portrait-con">
                <img src="../images/head.png"/>
            </div>
        </div>
        <p class="cir"><i></i>张真</p>
        <p class="fansi-con">粉丝:304 | 关注:479</p>
        <span class="enter">进入主页</span>
    </div>
    <div class="review">
        <span></span>
        往期回顾
        <span></span>
    </div>
    <div class="peo-img5">
        <img src="../images/people6.png">
        <p>沈伟媛</p>
        <span>收藏女王24年成就一件事</span>
    </div>
</div>
</body>
</html>
