<?php include_once VIEWS_PATH."/public/head.phtml";?>
<link href="<?php echo STATIC_DOMAIN;?>/css/guide.css" type="text/css" rel="stylesheet">
<?php if($origin==3){?>
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_01.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_02.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_03.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_04.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_05.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_06.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_07.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_08.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_09.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_10.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_11.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_12.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_13.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_14.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_15.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_16.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_17.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_18.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_19.jpg">
<img src="<?php echo STATIC_DOMAIN;?>/images/guide/use_20.jpg">
<?php }else{?>
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_01.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_02.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_03.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_04.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_05.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_06.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_07.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_08.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_09.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_10.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_11.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_12.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_13.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_14.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_15.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_16.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_17.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_18.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_19.jpg">
    <img src="<?php echo STATIC_DOMAIN;?>/images/guide/a_use_20.jpg">
<?php }?>
<!-- 返回顶部 -->
<div class="back-top font-ico up-ico back_top" title="返回顶部" style="display: none;"></div>
</body>
</html>