<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
    <script src="<?php echo STATIC_DOMAIN;?>/js/lib/appframework/appframework.js" type="text/javascript"></script>
    <script src="<?php echo STATIC_DOMAIN;?>/js/lib/appframework/plugins/af.popup.js" type="text/javascript"></script>

    <script type="text/javascript" src="<?php echo STATIC_DOMAIN;?>/js/page/common.js"></script>
    <link href="<?php echo STATIC_DOMAIN;?>/css/style.css" type="text/css" rel="stylesheet">
    <title>喜欢列表</title>
</head>
<body>
<div class="content">
    <div class="fans-list">
        <?php if(isset($user_list) && $user_list){?>
        <?php foreach($user_list as $key=>$val){?>
        <div class="fans-part layout-box active-e half-bor-bottom">
            <a class="user-pic fl d-block">
                <img class="b-radius-3" data-src="" src="<?php echo Common::show_img($val['avatar'],1,120,120);?>" width="60" height="60">
                <?php if($version >= '2.3'){?>
                <i class="<?php echo $val['ico_type'];?>"></i>
                <?php }?>
            </a>
            <div class="son-box user-info">
                <p><a class="font-18 blue"><?php echo $val['nick_name'];?><i class="<?php if($val['sex']==1){?>men<?php }else{?>women<?php }?> font-ico"></i></a></p>
                <p class="gray txt-cut text-small pad"><?php echo $val['intro'];?></p>
                <p class="gray text-small"><span>关注:<?php echo $val['att_num'];?></span><span>粉丝:<?php echo $val['fans_num'];?></span></p>
            </div>
            <div class="right-btn">
                <?php if($val['relation']==1){?>
                    <div class="fans-btn font-ico focus-btn"><i></i>已关注</div>
                <?php }elseif($val['relation']==2){?>
                    <div class="fans-btn font-ico friend-btn"><i></i>知己</div>
                <?php }else{?>
                    <?php if(isset($user) && $val['uid'] == $user['uid']){?>
                    <?php }else{?>
                        <div class="fans-btn add-btn" data-uid="<?php echo $val['uid'];?>"><i></i>关注</div>
                    <?php }?>
                <?php }?>
            </div>
        </div>
        <?php }}?>
    </div>
    <script>
        $(document).ready(function(){
            $('.fans-list').delegate('.fans-btn.add-btn','click',function(){
                var self = $(this);
                ajaxPost('/follow/addFollow',{f_uid:self.data('uid'),token:token},function(data){
                    if(data == 1) {
                        self.parent().append('<div class="fans-btn font-ico focus-btn"><i></i>已关注</div>');
                        self.remove();
                    } else if(data == 2) {
                        self.parent().append('<div class="fans-btn font-ico friend-btn"><i></i>知己</div>');
                        self.remove();
                    } else {
                        console.log(data);
                    }
                },function(data){
                    if(data.status == 403) {
                        backLogin();
                    } else {
                        tips(data.message);
                    }
                });
            });
        });
    </script>
</div>
</body>
</html>