<?php include_once VIEWS_PATH."/public/commonHead.phtml";?>
<body>
<div class="header">
    <div class="tiezi_toptar">
        <ul>
            <li class="tb_btn btn1"><a href="/fanhui"><img src="<?php echo STATIC_DOMAIN;?>/images/topic/top-btn1-1.png" id="img1"></a></li>
            <li class="top_title">帖子</li>
            <?php if(isset($user) &&($is_join['role'] == 1 || $is_join['role'] == 2 || $topicInfo['uid'] == $user['uid'])){?>
                <li class="tb_btn btn2" onclick="resetOperation();"><a><img src="<?php echo STATIC_DOMAIN;?>/images/topic/top-btn2-2.png" id="img2"></a></li>
            <?php }?>
            <li class="tb_btn btn3"><a href="/fenxiang/id/<?php echo $topicInfo['id']?>"><img src="<?php echo STATIC_DOMAIN;?>/images/topic/top-btn3-3.png" id="img3"></a></li>
        </ul>
    </div>
</div>
<!--tiezi_toptar  ed-->


<div class="scroll" id="scroll" style="width: 100%;">
    <div class="tiezi_cotent">
    <div class="tz_box tz_box1">
        <p class="tz_tit">
            <?php if($topicInfo['is_recommend']==1){?>
                <span class="top_btn btn_red">公告</span>
            <?php }?>
            <?php if( 1 == $topicInfo['is_top'] ){ ?>
                <span class="top_btn btn_blue">置顶</span>
            <?php }?>
            <?php if( 1 == $topicInfo['is_good'] ){ ?>
                <span class="top_btn btn_yellow">精</span>
            <?php }?>
            <?php echo $topicInfo['title'];?></p>
        <div class="tz_tit_xia"><span class="name" onclick="location.href='/user/<?php echo $topicInfo['user']['uid'];?>'"><?php echo $topicInfo['user']['nick_name'];?></span><?php echo Common::show_time($topicInfo['add_time']);?>&nbsp;[<?php if($topicInfo['type']==0){?>原创<?php }elseif($topicInfo['type']==1){?>转载<?php }else{?>才府独家<?php }?>]<span class="liulan"><img src="<?php echo STATIC_DOMAIN;?>/images/topic/tie-btn1.png"><?php echo $topicInfo['view_num']?></span> </div>
    </div>
    <!--标题  ed-->
    <div class="tz_box tz_box2 top-none">
        <div class="tz_p" >
            <?php echo $topicInfo['content']?>
        </div>

        <p class="tz_ban">本文的所有图、文等著作权及所有权归原作者所有<a href="/jubao/type/4/id/<?php echo $topicInfo['id'];?>">举报</a></p>
        <!-- 喜欢列表 -->
        <div class="tz_zan">
            <div class="tz_zan_s">
                <a>
                    <?php if(isset($topicInfo['is_like'])&&$topicInfo['is_like']){?>
                        <span id="like_status" class="zan_blue"></span>
                    <?php }else{?>
                        <span onclick="like(this)" data-type="4" data-id="<?php echo $topicInfo['id'];?>" id="like_status" class="zan_gray"></span>
                    <?php }?>
                    <p class="like"><span id="like_num"><?php echo $like_list['size'];?>人</span>喜欢</p>
                </a>
            </div>
            <?php if($like_list['size']==0){?>
                <div id="like_text"><p class="tz_zan_no">您的喜欢是对我最大的鼓励</p></div>
            <?php }?>
            <div class="like_user_more">
                <?php include_once VIEWS_PATH . "/center/likeUserList.phtml";?>
            </div>
        </div>
        <!-- 喜欢列表end -->
    </div>
    <!--详情介绍  ed-->
    <!-- 打赏列表 -->
    <div class="reward-list">
        <?php include VIEWS_PATH . "/common/rewardList.phtml";?>
    </div>
    <!--打赏列表  ed-->
    <div class="tz_box tz_box4">
        <div class="tz_box_title clearfix">
            <li class="x1"></li>
            评论
            <li class="x3"></li>
        </div>
        <div class="tz_pinglun">
            <div class="pl_list clearfix">
                <?php if(isset($user) && $user){?>
                    <div class="pl_l">
                        <div class="angel_box" onclick="location.href='/user/<?php echo $user['uid'];?>'">
                            <img class="ds_photo" src="<?php echo Common::show_img($user['avatar'],1,80,80)?>">
                            <i class="<?php echo $user['ico_type'];?>"></i>
                        </div>
                    </div>
                <?php }else{?>
                    <div class="pl_l"><img class="ds_photo" src="<?php echo STATIC_DOMAIN;?>/images/topic/tie-photo.jpg"></div>
                <?php }?>
                <div class="pl_r">
                    <div class="pl_r_con">
                        <a href="/comment/token/<?php echo $token?>/type/4/id/<?php echo $topicInfo['id'];?>/replyuid/<?php echo $topicInfo['uid'];?>/replyid/0" type="text" >
                            <p class="pl_r_text">
<!--                                <input type="text" placeholder="我要评论"  />-->
                                <span type=text"">我要评论</span>
                            </p>
                        </a>
                    </div>
                </div>
            </div>
            <!--评论列表-->
            <div class="comment_list">
                <?php include_once VIEWS_PATH . "/common/comment.phtml";?>
            </div>
            <div class="pl_message">
                <div class="mes_top">
                    <p class="mes_bg">
                    </p>
                    <p class="mes_photo" onclick="location.href='/user/<?php echo $topicInfo['user']['uid'];?>'">
                        <img src="<?php echo Common::show_img($topicInfo['user']['avatar'],1,160,160)?>">
                        <i class="angel2 <?php echo $topicInfo['user']['ico_type'];?>"></i>
                    </p>
                </div>
                <p class="mes_name" onclick="location.href='/user/<?php echo $topicInfo['user']['uid'];?>'"><?php echo $topicInfo['user']['nick_name'];?></p>
                <p class="mes_fensi"></p>
                <a href="/user/<?php echo $topicInfo['user']['uid'];?>'" class="mes_guanzhu">进入主页</a>
            </div>
        </div>
    </div>
    <!--记录 ed-->
    <div class="tz_box tz_box5 bottom-none">
        <div class="tz_box_title clearfix">
            <li class="x1"></li>
            看了又看
            <li class="x3"></li>
        </div>
        <div class="tz_neirong">
            <?php foreach($newList as $val){?>
                <div class="tz_nei_list clearfix">
                    <p class="n_left" ><a href="<?php echo $val['url'];?>"><img src="<?php echo $val['img']."?imageMogr2/thumbnail/!240x240r/gravity/North/crop/240x240"?>"></a></p>
                    <div class="n_right">
                        <div class="nr_container">
                            <p class="nr_tit ellipsis" onclick="location.href='<?php echo $val['url'];?>'"><?php echo $val['title'];?></p>
                            <p class="nr_jieshao" onclick="location.href='<?php echo $val['url'];?>'"><?php echo Common::msubstr($val['summary'],0,27);?></p>
                            <ul class="nr_xia">
                                <li class=" nr1" onclick="location.href='/user/<?php echo $val['user']['uid'];?>'"><img src="<?php echo STATIC_DOMAIN;?>/images/topic/fuwu-ico10.png"><?php echo $val['user']['nick_name'];?></li>

                            </ul>
                        </div>
                    </div>
                </div>
            <?php }?>
        </div>
        <p class="ds_jilu_more"><a href="/goodTopicMore">更多帖子<img src="<?php echo STATIC_DOMAIN;?>/images/topic/tie-btn2.png"></a></p>
    </div>
    <!--相关内容  ed-->
</div>
</div>
<!--tiezi_content  ed -->
<div class="footers">
    <div class="tiezi_bottom clearfix">
        <ul>
            <li class="bbtn1"><a href="/dashang/token/<?php echo $token?>/type/4/id/<?php echo $topicInfo['id'];?>"><span class="bottom_ico bottom_ico_rewrad"></span>打赏</a></li>
            <?php if(isset($topicInfo['is_collect'])&&$topicInfo['is_collect']==1){?>
                <li class="bbtn2_hover" id="like_li_status"  data-type="4" data-id="<?php echo $topicInfo['id'];?>" onclick="RemoveCollection(this)"><a id="like_a_status"><span class="bottom_ico bottom_ico_like_hover"></span>已收藏</a></li>
            <?php }else{?>
                <li class="bbtn2" onclick="Collection(this)" id="like_li_status"  data-type="4" data-id="<?php echo $topicInfo['id'];?>"><a id="like_a_status"><span class="bottom_ico bottom_ico_like"></span>收藏</a></li>
            <?php }?>
            <li class="bbtn3"><a href="/yizhan/sid/<?php echo $topicInfo['sid'];?>"><span class="bottom_ico bottom_ico_post"></span>驿站</a></li>
            <li class="bbtn4"><a href="/comment/token/<?php echo $token?>/type/4/id/<?php echo $topicInfo['id'];?>/replyuid/<?php echo $topicInfo['uid'];?>/replyid/0">我要评论</a></li>
        </ul>
    </div>
</div>
<!--tiezi_bottom  ed-->
<div class="bottom-label">
    <ul style="display: none">
        <?php if((isset($user)&&$topicInfo['uid'] == $user['uid'])){  ?>
            <li class="label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" data-url="/topic/delTopic" onclick="delContent(this);">删除</li>
           <!-- <li class="label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" onclick="location.href='/bianji/type/4/id/<?php echo $topicInfo['id']?>/token/<?php echo $token?>'">编辑</li>-->
        <?php }?>
        <?php if ($is_join['role'] == 1 || $is_join['role'] == 2){ ?>
            <?php if($topicInfo['is_top']==1){ ?>
                <li data-type="1" class="cancel-top label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" data-url="/topic/cancelTop" onclick="cancelOperation(this);">取消置顶</li>
            <?php }else{ ?>
                <li data-type="1" class="tops label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" data-url="/topic/top" onclick="operation(this);">置顶</li>
            <?php } ?>
            <?php if($topicInfo['is_good']==1){ ?>
                <li data-type="2" class="cancel-top label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" data-url="/topic/cancelTop" onclick="cancelOperation(this);">取消加精</li>
            <?php }else{ ?>
                <li data-type="2" class="tops label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" data-url="/topic/top" onclick="operation(this);">加精</li>
            <?php } ?>
            <?php if($topicInfo['is_recommend']==1){ ?>
                <li data-type="3" class="cancel-top label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" data-url="/topic/cancelTop" onclick="cancelOperation(this);">取消公告</li>
            <?php }else{ ?>
                <li data-type="3" class="tops label_btn" data-id="<?php echo $topicInfo['id'];?>" data-token="<?php echo $token;?>" data-url="/topic/top" onclick="operation(this);">公告</li>
            <?php }
        } ?>
        <li class="label_btn cancel"><a>取消</a></li>
    </ul>
</div>
<script>
    var scrollable = document.getElementById("scroll");
    new ScrollFix(scrollable);
    function resetOperation(){
        $(".bottom-label ul").css("display","block")
        $(".bottom-label").addClass("am-modal-active");
        if($(".labelbg").length>0){
            $(".labelbg").addClass("labelbg-active");
        }else{
            $("body").append('<div class="labelbg"></div>');
            $(".labelbg").addClass("labelbg-active");
        }
        $(".labelbg-active,.cancel").click(function(){
            $(".bottom-label").removeClass("am-modal-active");
            $(".bottom-label ul").css("display","none")
            setTimeout(function(){
                $(".labelbg-active").removeClass("labelbg-active");
                $(".labelbg").remove();
            },200);
        })
    }
</script>
</body>
</html>